services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=db_florist'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
      - 'MYSQL_PASSWORD=florist'
      - 'MYSQL_USER=emman'
    ports:
      - '3306:3306'